### ISSUE TITLE
Inputs to ranges and airspace

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/TRMA#1]
Please post discussions about suggestions and inputs for ranges and airspace in this issue

**Comment by 132ndNeck** [comment]
Very rough initial idea to get the ball rolling.
Bodø airbase will be the base where 132nd is based. 

![bilde](https://github.com/132nd-vWing/TRMA/assets/26002570/dc0920c4-6922-4e84-8728-891862cbfa77)

CombatFlite file:
https://drive.google.com/file/d/1JpheA6aXCInvRilJXJvk2h3VKX_G0Tnt/view?usp=sharing

**Comment by Gabykhan** [comment]
In my opinion, it's counter-productive to start a layout at this point.
We should analyze particular training needs and requests, and then only from this analysis decide how to fullfill them.
Also, I would personally like to use as much as possible real life airspace, in particular in order to be able to use real airfield procedures, that require specific airspaces (TMA, CTR, etc...).

**Comment by jkhoel** [comment]
Unless we are changing fundamental principles of our training maps, then peace- vs wartime is not a thing. Training maps are always peacetime. The concept of "range rings" to dictate locations I like, but I want to use your argument with regards to airspace against you ;) I want the ranges to be where they are in real life, so that we can use the same procedures etc.

**Comment by 132ndMagnet** [comment]
Dropping thoughts before I forget them :-)

- Instead of establishing defined VFR arrival and departure routes, create VRPs (visual reporting points - real world preferred) on the boundaries of the TMA. This should result in a more flexible arrival and departure situation as at present I think pilots feel that they have to use one of the published VFR departures and therefore are potentially flying out of the TMA in the wrong direction to then route around or over the TMA to get where they wish to go. As an example on the current map, this would allow a pilot to be given the following clearance if Rwy 31R was active, 'VIPER 1, right hand turn out, cleared to leave the TMA via X-Junction, not below 6000ft QNH 3004'.

- Real world frequencies for ATC positions

- Real world IFR approaches (as far as possible) e.g. ILS Z or LOC Z Rwy 07, VOR Rwy 07, ILS or LOC Rwy 25 (Vector to final should be the default when ATC is online, i.e. not Full Approaches)

- Is it practical to have a frequency plan where all aircraft based at the training aerodrome have the Ground, Tower, Radar & Talkdown frequencies in the same preset number, e.g. Ground is preset 2, Tower preset 3 etc? This would enable transfer without reading out the frequency and be more 'military'. e.g. 'VIPER 1, Contact Tower, Preset\Stud 3'.

**Comment by 132ndEvo** [comment]
Hello all. I've made a draft of SID and STARs for ENBO. I would strongly recommend we use this system for a few reasons. 
1. High terrain makes it vital that aircraft follow routes for terrain clearance.
2. The routes offer both vertical and lateral separation allowing for ops in IMC without a controller.
3. The routes are designed for an airspace 25 nm around BODO.
4. The routes are made using real-world way points will allow us to use the real world approach, SID and STAR charts. 

take a look and let me know what you think.
Thanks
https://www.dropbox.com/scl/fi/euewa6zotgpdmpr19izk0/TRMA-ENBO-SID-STAR-Evo.cf?rlkey=6ivpxi5491uvf14xj9hbcvmqs&st=mdzn4hf3&dl=0

**Comment by Gabykhan** [comment]
Evo, the FLIP shared on the Real Life data thread has the military departure and recovery procedures.
It's perfect for IMC operations.
For VMC, we can either try to find the real procedures, or build new ones with easy in game visual references.

**Comment by Shadoga** [comment]
My position on TRMA / ENBO procedures:

[Shadow TRMA ENBO Procedures Opinion Paper 20240518.docx](https://github.com/132nd-vWing/TRMA/files/15363141/Shadow.TRMA.ENBO.Procedures.Opinion.Paper.20240518.docx)
[Shadow TRMA ENBO Procedures Opinion Paper 20240518.txt](https://github.com/132nd-vWing/TRMA/files/15363144/Shadow.TRMA.ENBO.Procedures.Opinion.Paper.20240518.txt)

![176th TRMA ENBO TMA Request](https://github.com/132nd-vWing/TRMA/assets/168900540/51353450-cd82-433c-975b-45fb423347e3)
![176th TRMA ENEV ENAN ENDU ENTC TMAs Request](https://github.com/132nd-vWing/TRMA/assets/168900540/640f1855-480b-45e4-a414-989d61ea3fdf)

[CENOR FLIP EN_AD_2_ENBO_en.pdf](https://github.com/132nd-vWing/TRMA/files/15363166/CENOR.FLIP.EN_AD_2_ENBO_en.pdf)
[ENBO Copter RNP 117 Approach.pdf](https://github.com/132nd-vWing/TRMA/files/15363167/ENBO.Copter.RNP.117.Approach.pdf)
[ENBO Omnidirectional SID RWY07 Text.pdf](https://github.com/132nd-vWing/TRMA/files/15363168/ENBO.Omnidirectional.SID.RWY07.Text.pdf)
[ENBO Omnidirectional SID RWY25 Text.pdf](https://github.com/132nd-vWing/TRMA/files/15363169/ENBO.Omnidirectional.SID.RWY25.Text.pdf)
[ENBO SIDs SENEQ CAT H Chart.pdf](https://github.com/132nd-vWing/TRMA/files/15363170/ENBO.SIDs.SENEQ.CAT.H.Chart.pdf)
[ENBO SIDs SENEQ CAT H Text.pdf](https://github.com/132nd-vWing/TRMA/files/15363171/ENBO.SIDs.SENEQ.CAT.H.Text.pdf)
[ENBO TMA Chart.pdf](https://github.com/132nd-vWing/TRMA/files/15363172/ENBO.TMA.Chart.pdf)
[ENBO VAC Visual Approach Chart.pdf](https://github.com/132nd-vWing/TRMA/files/15363174/ENBO.VAC.Visual.Approach.Chart.pdf)

[TACAN Routes.pdf](https://github.com/132nd-vWing/TRMA/files/15363184/TACAN.Routes.pdf)

**Comment by 132ndNeck** [comment]
Closing this one and continuing the discussion on Issue #15 (finalizing airspace)
