### ISSUE TITLE
ATC on VHF or UHF?

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/TRMA#17]
Should we have ATC on VHF or UHF frequencies?

**Comment by hbjonsson** [comment]
UHF, for the love of Odin, UHF. This would avoid the happhazard radio shuffles of moving a flight to a separate radio during critical periods of coming and going to the airport.

If there is a platform that requires VHF, the controller could open up a backup VHF requency and transmit/cross couple the UHF and VHF radios.

**Comment by kimkiller65** [comment]
Just to be curious, aren't VHF the standard for Tower freqs?

**Comment by Gabykhan** [comment]
> Just to be curious, aren't VHF the standard for Tower freqs?

In general military airfields have both VHF and UHF frequencie. Jets tend to use primarily UHF ones. 
Just to give you an idea, here are NATO common frequencies (they are monitored on all airfields, and if you don't know an airfield frequency you can try on them):

Tower - 122.100, 257.800
Radar - 123.300, 344.000, 362.300, 385.400

**Comment by 132ndMagnet** [comment]
UHF, due to first comment and ATC can operate comfortably on either.

**Comment by RedDog132nd** [comment]
UHF: reason: first comment

**Comment by Shadoga** [comment]
UHF as standard for as many control services as possible.

I would however have a huge problem if the 176th controllers would be required to monitor the published VHF frequencies for the respective control service for potential use as well, doubling the number of frequencies to be monitored, the chance of simultaneous receptions, the difficulty to notice who talked where and the need to switch transmitters.
In the real world, this issue is solved by frequency cross-coupling at the frequencies-owning ground station: coupled frequencies are re-transmitting out an incoming transmission on all other coupled freqs so that everyone on every frequency can hear anyone talking on another one. This way block-outs prevent simultaneous receptions.
We don’t have that option in SRS yet, all you can do there is couple multiple transmitters to broadcast the controllers transmission on multiple frequencies - but you can’t couple multiple receivers for re-transmitting, which would be leading to the desired effect that air stations on different freqs hear each other as if they were on the same.
To be required to simultaneously monitor the VHF freqs for ENBO GND, TWR & APP in addition to the primary UHF freqs as a controller is not advisable.

Since the VHF frequencies for the ENBO ATC agencies are published on the real charts - and in case some DCS client for whatever reason is only VHF-capable, the way to go should look like this:
- Every controller monitors UHF and VHF Guard on his SRS "awacs overlay" all the time.
- A station requiring service via VHF radio calls that service provider on VHF Guard with the request.
- Only then will the controller start configuring SRS for that and commence working on his VHF as well.

VHF will be available "on request only".

**Comment by 132ndNeck** [comment]
UHF

**Comment by 132nd-Erro** [comment]
UHF seems to be the reasonable choice here, as per first comment. I don't think we have a platform in the Wing (or a future candidate) that would prefer VHF?

**Comment by 132ndNeck** [comment]
Based on the inputs, we can decide that we will use UHF for all ATC freqs.
