### ISSUE TITLE
ENBO Spawnpoints Coordination

### ISSUE THREAD

**Issue by Shadoga** [132nd-vWing/TRMA#20]
This issue serves the coordination between the squadrons and mission makers of who needs what and how the client spawnpoints (and suitable ground-spawn areas will be assigned.

Real estate in Bodo is a little more limited than in Al Dhafra, requiring realistic expectations, modest demands and the acceptance of compromises from everyone.

Some premisses:

- We are currently using 83 spawnpoints for the standard airframes in OMAM, not counting red air and airframes without and active squadron like Hip and Blackshark. (12xA10; 10xF14; 12xF15E; 21xF16; 12xF18; 16xH64)

- Bodo offers a minimum of the following spawnpoints: 13xLIMA; 32-40xKILO; 15xGOLF; 12xCHARLIE-FIVE; 2xYANKEE; 6xWHISKEY; 1xZULU; 8xGA (General Aviation).

- So ENBO has more than 83 possible spawnpoints, but I would like to keep some contingencies from squadron use for the time which might later be reassigned to new sqadrons.
Examples:
1. I want to keep the 12 spawnpoints on Ramp C-5 unused for the time and use the ramp exclusively for re-arming / refuelling and formation /package join-ups on the ground. Later it can be assigned to a whole new airframe squadron, if really required.
2. RedFor Adversaries might need more than just the 6 WHISKEY shelters in the North, but we should start there and then use the adjacent ramps for ground-spawn.
3. For rotor-wings, there are scattered pads in the south that could be used for ground-spawn, but you should also consider making youself comfortable on the nicely marked GA spawnpoints and their surroundings in the North.

Squadron Commanders should review their demands realistically together with their pilots to come up with a number request.
Grouping squadrons' spawnpoints together will for sure be a thing.
Of course you can also state any wishes on preferred locations, but in the end there might have to be a lottery about that...

Please everyone share your thoughts and any input here for a brainstorming.
Finally, only SQs, state your requests in a format similar to this example:
(not an actual coordinated request)

### 108th:
- 6 x F14B
- 6 x F14B Immortal
- 2 x F14A Immortal RedFor Adversary
- We want GOLF or LIMA to ourselves, incl. RedFor.
- Mission makers keep in mind that Red F14s will need an invisible red FARP very close by, otherwise no red ground crew support thus no startup.

**Comment by 132nd-Erro** [comment]
## 656th / rotary wing

The helicopters are currently located on yankee in the current TRMA version (v 2.1). This was suggested in a previous discussion (prior to the dedicated Discord channels), and we would like to keep it this way. It should be able to hold 12 helicopters in total, be it AH-64, OH-58, or CH-47. 

On yankee:
* 4x AH-64
* 4x AH-64 immortal

**Comment by hbjonsson** [comment]
# 495th / F15E's
Cutter asked me to request spots for the 495.
* 12 x F15Es
* [Agressor jets TBD]

We would like the jets to be set to "on ground" **outside** the HASs.

* 4 Ship on on K10, K11, K12, unmarked.
* 4 Ship on K16 and 18, K20 and K22.
* 4 Ship on K25, K26, K27 and K29.

( Note K17 and K19, K28 is not suitable. )

* There are 3-4 slots possible for expansion in a couple of blank spots + K32 if more jets are needed.

![image](https://github.com/132nd-vWing/TRMA/assets/25992707/39b2f696-23f8-46c8-b47d-11c4b7bce8f4)

**Comment by 132nd-Erro** [comment]
I am restating [this comment](https://github.com/132nd-vWing/TRMA/issues/15#issuecomment-2156614083) under this issue and elaborating a little bit further.

8 airframes as requested were placed as shown in the image below. (The red ring marks the area of the second image.) The area in the first image is too small even for the Apaches to operate, but it is not accessible by all helicopters using taxi ways. 
![image](https://github.com/132nd-vWing/TRMA/assets/101829260/a1bb9416-4786-4839-9500-6b4b76c96e14)

Instead, the area as shown here at C-5 (Y01-Y12) should provide us with sufficient space and connections using taxi ways.
![216dd547-383b-40f8-9215-21af3b3bfcdf-1](https://github.com/132nd-vWing/TRMA/assets/101829260/b8277200-b7ac-4bb4-9a23-889e2e27c508)

Some points on the desired RW location on C-5 vs unmarked area in the first image:
* The Apache can hover taxi by crossing the grass, but that is not always possible, depending on loadout, temperature and wind. We often practice and have to perform rolling take-off due to conditions and loadout.
* It is not possible to maintain visual contact with all helicopters in the flight. Even in the current ATRM we struggle with this, but our SOP states (back from the 696th days too) that we initiate comms check by observing the navigation lights; once they are on we initiate the check. This is the only ramp on the south side that allows the flight to maintain visual with eachother.
* As the slowest movers, when considering the total time of flight, C-5 at the center of the runway facilitates a short start-up to take-off time when having to utilize the runway for departures.
* The images as shown place two Kiowa sections on the grass, I coordinated with Sly and he said that since they have skids to begin with, and always have to hover taxi, they could have some helicopters placed on the grass with FARPs or Helipads instead. 
* There are locations to the north, but since RW will mostly depart to the south to the RW ranges, being on the south side of the RWY can be beneficial to deconflict and schedule direct departures.

**Comment by Shadoga** [comment]
From a 176th point of view, having most rotorwing operations on the northern maneuvering areas of the airport remains by far preferable:
- The North features the Helipad(s) plus the 4 FATO and TLOF Areas marked on TWY W. https://www.halibrite.com/heliport-lighting/fato-and-tlof-areas-ensures-safety-landing-and-takeoff/
- TWY W is the preferable contingency for rolling RW takeoffs and landings when the main runways capacitiy is under high demand. This contingency is not available on TWY Y in the South during high traffic loads amidst taxiing fixed wings.
- Simultaneous fixed wing (jet blast) and RW (downwash) taxi / hover-taxi operations on TWY Y require spacing and caution, the mainly use of parallel TWY W for RW would vastly increase aerodrome taxi capacities.
- RW crossings to / from the South via overflying the main RWY or via crossing East or West of the respective thresholds are not problematic capacity-wise because they take only short amounts of time.
- Ramp C-5 could for the time be kept clear from spawns and thus be made available for all platforms for intermediate re-arming / refuelling or for ground join-ups of flights or even whole packages. In the future, it could then still be used as spawn area for a whole new airframe squadron without havin to relocate the RWs then, if no more capacities on L, K and G can be made available.

![ENBO Aerodrome Ground Chart v01](https://github.com/132nd-vWing/TRMA/assets/168900540/b193225c-2f94-4ce4-9085-a133ab028503)
![ENBO Aircraft Parking Chart v01](https://github.com/132nd-vWing/TRMA/assets/168900540/1b5e99df-8f9a-454a-bd54-0fabb3ed4e7b)

**Comment by 132nd-Erro** [comment]
> The North features the Helipad(s) plus the 4 FATO and TLOF Areas marked on TWY W. https://www.halibrite.com/heliport-lighting/fato-and-tlof-areas-ensures-safety-landing-and-takeoff/

These are nicely laid out helipads for singletons and civilian helicopters, but they are not good positions for helicopters that intend to start up and taxi together as a flight. Another option is to ignore the ground markings and just place the helicopters wherever there's room, but I don't think that's according to SOP or regulations either. 

C-5 is by far the best apron for helicopters I've seen that will operate as a flight of 2 or 4, and that includes the airfields we've operated from in PG and Syria too. 

   > TWY W is the preferable contingency for rolling RW takeoffs and landings when the main runways capacitiy is under high demand. This contingency is not available on TWY Y in the South during high traffic loads amidst taxiing fixed wings.

When doing rolling take-offs we should use the runway, in these situations (possibly unless for training) we are heavy, underpowered and need the extra width that only the runway has. We would never do a rolling take-off from a taxiway, but we would (and often) do a direct departure from the apron by a hover onto the nearest taxiway, then speed up and climb until we turn to where we want to go. This is how we do it at Al Ain when there are no FW around, as it is preferable over maximum-power (towering) take-offs amidst high light poles. 

We could do it like that when there is low/now traffic on the taxiways close to C-5, by hovering onto TWY Y to the east, then departing in between taxi ways where FW will move along. Just stating this as an option and not necessarily something to standardize.
![image](https://github.com/132nd-vWing/TRMA/assets/101829260/c33483e7-6cef-4b7f-bf4c-13ad4bac2abd)

> Simultaneous fixed wing (jet blast) and RW (downwash) taxi / hover-taxi operations on TWY Y require spacing and caution, the mainly use of parallel TWY W for RW would vastly increase aerodrome taxi capacities.

All taxi operations require spacing and caution, we have operated with FW on both Al Ain and Al Dhafra in the past without spacing being problematic when flights hold short of others on taxi ways.

Lastly, as I edited in above, it would be nice for us to be on the same side of the runway close to the rest of the Wing. This also excludes the locations at the very south of the area close to the sea. It is nice to see other holding and taxiing traffic up close, and not as outsiders just observing something happening on the other side.

**Comment by victrox-dev** [comment]
I can genuinely see the argument for C-5 as re-arming/re-fueling/join-up pad for fixed wing assets and it's unfortunate that we don't have more space to work with at this airfield. Provided the space that we _do_ have, we need to come to an agreement on this or find an alternative solution _together_.

First and foremost, I think it's important to maintain a strong sense of community within the 132nd, and I firmly believe placing the rotary wing assets in the general aviation area will be counter-productive to that effort. Personally, I don't want to be segregated from the rest of the wing, and I believe that will be the perception of future RW trainees if we are stuck to the North; as if we don't belong or have a place here. I'm used to this feeling of isolation so it doesn't bother me, but I don't want that to be the impression of future RW trainees coming into the wing. I think I speak for most everyone in the 132nd when I say the largest contributing factor to the enjoyment we experience as a group is due to the fact that we _are_ a group of like-minded individuals that enjoy participating and coordinating in events together.

Now, it's important to note that my own feelings of isolation from the wing are not the fault of anyone specific, it's just the way things have developed overtime. We frequently depart from far-off FARPs or OMAL during standard training because we need to utilize the ranges to the East and it's unreasonable for us to take a one hour flight from OMAM to achieve our training objectives. I recognize that's not an intentional design on the part of anyone trying to push us away, and I appreciate the effort that has gone into securing RW ranges close to ENBO so that this doesn't continue to be an issue moving forward. That alone resolves a lot of problems.

With the feelings and perception part of the equation out of the way... speaking as a 656th IP now, we can't take the unmarked area as Erro noted it prevents us from performing a ground taxi due to spacing. From a realism perspective, I don't believe the military would leave unattended Apache's in GA parking; this is the case for the U.S. Army, anyway. A crew-chief would be sleeping in that aircraft while the pilots are in a cozy hotel. Perhaps Norway trusts their citizens a little more? lol

Ideally, the 656th should be on the C-5 ramp. But understanding concerns from both parties I've come up with an alternate solution that (hopefully) appeases everyone. I've come to the table offering this (not yet reviewed by Erro):
Utilize rectangular trigger zones and a mission start trigger to remove scenery objects IVO K31, eight (8) Apache's fit nicely on the pad there and have access to a taxiway.
![image](https://github.com/132nd-vWing/TRMA/assets/62825656/f1d73b47-cc61-43d8-94aa-5771a291fb13)

![Screen_240610_171124](https://github.com/132nd-vWing/TRMA/assets/62825656/5b545acd-a3db-47f2-95f4-9b3d3a81d7c1)

![Screen_240610_171138](https://github.com/132nd-vWing/TRMA/assets/62825656/17e48c72-b1bc-4220-8ac5-9d689c2b6dd0)

Additionally, although the 24th has not yet been approved, seven (7) Kiowa Warriors fit nicely IVO K23.
![Screen_240610_171204](https://github.com/132nd-vWing/TRMA/assets/62825656/d8f20a75-b979-4777-bbe6-dcfd1a109f4e)

![Screen_240610_171209](https://github.com/132nd-vWing/TRMA/assets/62825656/3ca612fd-82ab-4e08-a431-1d45e5383d2f)

**Comment by victrox-dev** [comment]
I can genuinely see the argument for C-5 as re-arming/re-fueling/join-up pad for fixed wing assets and it's unfortunate that we don't have more space to work with at this airfield. Provided the space that we _do_ have, we need to come to an agreement on this or find an alternative solution _together_.

First and foremost, I think it's important to maintain a strong sense of community within the 132nd, and I firmly believe placing the rotary wing assets in the general aviation area will be counter-productive to that effort. Personally, I don't want to be segregated from the rest of the wing, and I believe that will be the perception of future RW trainees if we are stuck to the North; as if we don't belong or have a place here. I'm used to this feeling of isolation so it doesn't bother me, but I don't want that to be the impression of future RW trainees coming into the wing. I think I speak for most everyone in the 132nd when I say the largest contributing factor to the enjoyment we experience as a group is due to the fact that we _are_ a group of like-minded individuals that enjoy participating and coordinating in events together.

Now, it's important to note that my own feelings of isolation from the wing are not the fault of anyone specific, it's just the way things have developed overtime. We frequently depart from far-off FARPs or OMAL during standard training because we need to utilize the ranges to the East and it's unreasonable for us to take a one hour flight from OMAM to achieve our training objectives. I recognize that's not an intentional design on the part of anyone trying to push us away, and I appreciate the effort that has gone into securing RW ranges close to ENBO so that this doesn't continue to be an issue moving forward. That alone resolves a lot of problems.

With the feelings and perception part of the equation out of the way... speaking as a 656th IP now, we can't take the unmarked area as Erro noted it prevents us from performing a ground taxi due to spacing. From a realism perspective, I don't believe the military would leave unattended Apache's in GA parking; this is the case for the U.S. Army, anyway. A crew-chief would be sleeping in that aircraft while the pilots are in a cozy hotel. Perhaps Norway trusts their citizens a little more? lol

The 656th should be on the C-5 ramp. I’ve personally exhausted all other options on the Southern side of the airfield (to include scenery removal) and nothing else is going to reasonably support us. I had previously suggested scenery removal IVO K31 and it turns out there’s not enough space there to safely conduct hover checks with the other aircraft spawned on the same pad. In the interest of keeping RW close to each other, I’m willing to accept the grass IVO C-5 for the Kiowas (not yet approved but planning for the future and keeping fingers crossed).

**Comment by Shadoga** [comment]
108th requests:

- 4 x F-14B (K06, K09, K13, K14)
- 6 x F-14B Immortal (K08, K07, K02, K04, K01, K03)
- 2 x F-14B RedFor Immortal
- 2 x F-14A RedFor Immortal

- Alternative spawnpoint request would be to have all 10 blue jets in Shelter Loop GOLF.
- We request the jets to spawn "on ground" outside the shelters.

**Comment by 132ndNeck** [comment]
I will likely spread squadrons around, and they will not be parked close to each other. That way, each squadron can have some jets close to the center of the runway (for the most events when they have not a full squadron participating. This in order to reduce taxi times and "admin time" that takes away from training objectives). For the events where the full squadron is attending, there will be more parking spots, possible on each side of the runway, again to be able to pick jets to reduce taxi time as much as possible).

**Comment by 132ndNeck** [comment]
> and I firmly believe placing the rotary wing assets in the general aviation area will be counter-productive to that effort. Personally, I don't want to be segregated from the rest of the wing, and I believe that will be the perception of future RW trainees if we are stuck to the North; as if we don't belong or have a place here. 

I think if we are all on the same airbase, it is about using the real-estate that is available to us for maximum utilization. There will be FW aircraft placed in shelters on the northern side of the runway, just as in real life, and that should not make someone feel they are not a part of the community.

> We frequently depart from far-off FARPs or OMAL during standard training because we need to utilize the ranges to the East and it's unreasonable for us to take a one hour flight from OMAM to achieve our training objectives. I recognize that's not an intentional design on the part of anyone trying to push us away, and I appreciate the effort that has gone into securing RW ranges close to ENBO so that this doesn't continue to be an issue moving forward. That alone resolves a lot of problems.

This is something the RW community have wanted and have done on their own. The goal for me as the mission designer have alway been to operate from the same airbase. The reason why we are blocking off large part of airspace in the TMA in order to facilitate specific RW training. So we need should also that fact into consideration when we are discussing the feeling about beeng part of the wing and group, and not necessarily if one are on the north or south side of the runway.

> speaking as a 656th IP now, we can't take the unmarked area as Erro noted it prevents us from performing a ground taxi due to spacing

This is a very good and valid argument, and is more than enough reason for me to not place the AH-64s on that grey unmarked area.


> From a realism perspective, I don't believe the military would leave unattended Apache's in GA parking; this is the case for the U.S. Army, anyway. A crew-chief would be sleeping in that aircraft while the pilots are in a cozy hotel. Perhaps Norway trusts their citizens a little more?

We are flying in a simulator for fun. It is easy to take in a realism argument whenever it suits ones view. We need to make our decisions on what work best for us as wing, having this as a hobby. We want to do things realistically, but not real world. So security issues regarding where aircraft are parked when we are not in the sim should be very low on the priority list over items we need to consider. We are already using live fire and dropping bombs all around the civilian population, or have red units firing at us for training purpose, so we have breached the realistic approach a while ago. My point is that we should not just pick and choose realistic as a argument when it supports or view. Of course, it is important to bring it into the conversation as one of the items to consider, but it need to be weighted against everything else.

**Comment by 132ndNeck** [comment]
They key point that is missing in the discussion is @Shadoga's point regarding join-up of flights/packages from the various shelter loops, as they may be spread around. The C-5 area are the only suitable area for that, except we want aircraft to taxi to the other side of the runway to join up, and then taxi back to the runway for departure.

> We could do it like that when there is low/no traffic on the taxiways close to C-5, by hovering onto TWY Y to the east, then departing in between taxi ways where FW will move along. Just stating this as an option and not necessarily something to standardize.

In general with the amount of FW taxing on  TWY Y will likely make it busy, so using TWY W for this is likely a better suggestion.

We need to think about the flow for the entire wing on a training night with 30+ RW and FW operating, and not isolate it into what is best only for one community. The advantage of the northern area is to have one large parking area that allows the entire RW community be in one area. FW jets will also be based on the shelters on the northern side of the runway, so the argument of not beeing part of the wing is not a very good one I think.  In the current test&eval there are not, but that is simply because I only have placed jets in for the purpose of the testing and not populating the entire map

**Comment by Shadoga** [comment]
I'm with Neck on the philosophy to use the whole airport / airbase real estate for the Wing and also for the Wing's future as best a compromise as we can.
Yes, it might feel initially a little unrealistic to spawn on the civilian side and use the civilian markings and to see the Terminal and Docking Gates up close.
But then, our ENBO has no civilian co-use, there will be no civilian static or A.I. traffic anywhere.
We have annexed the whole aerodrome for military training use and we want to station initially 5 FW plus 2 RW squadrons there. Within weeks, a 3rd RW squadron (H47) might appear, and over the next months and years, more FW squadrons are very likely to be formed (C130, F4, EUFI, A6, TOR).
If we have the whole airbase to ourselves, if we want to make ourselves cozy at home there and make best use of all facilities right from the start for the present and the future, then some things are strikingly obvious from a Wing / Base commanders and an ATC controllers point of view:
- The shelter loops south of the RWY are ideal only for HPMA spawnpoint use. They should be used for present and future HPMA squadrons until maxed out. The landscape, installations, vegetation and TWY width of the shelter loops make them unusable for larger FWs like future C130 and not desirable for taxi and hover-taxi use by RWs.
- The WHISKEY and ZULU Shelters including the small ramp (spawnpoint W03) in front of the real world Wideroe Airlines Maintenance Hangars are an ideal area for concentrating all RedFor adversary airframe spawnpoints.
- The CIV APRON is the ideal large area for large FW spawnpoints, like e.g. future C130s. Having those taxi on TWY W instead of an already crowded TWY Y is the only right thing to do ground-operation-capacity-wise.
- The Helipad H01 and the GA spawnpoints are the ideal area for spawnpoints, hover-checks and operational base for RWs. Having them taxi to the RWY on TWY W instead of TWY Y will be more efficient and make best use of available ground maneuvering areas. Plus, having the contingency option to let them operate from TWY W, the 4 FATO and TLOF Areas and the Helipad, naturally frees up RWY capacities during those times when traffic demand exceeds RWY, TWY or Pattern / Airspace capacities. The argument that TWY W is not wide enough for rolling take-offs & landings is operational nonsense regarding a TWY width of 23m (31m incl. shoulders) versus the wheel widths and rotor diameters (H64 14,6m; H47 18m) of present and future RWs.
- The C-5 Ramp is the ideal small ramp for all sorts of flexible non-spawn use south of the RWY: join-up / "last chance" use by flights and even whole packages, intermediate re-arming / refuelling, overtaking / delaying taxi operations for TWY Y, etc. It should be kept clear from any spawns as long as possible, until the southern shelter loops are maxed out - only then should it be re-commisioned to host the 12 spawnpoints for a whole new HPMA squadron.
- TWY Y will be a severe bottle-neck during high-capacity-demand departure and arrival phases, if it's solely used for all military traffic, including transports, RWs and RedFor adversary HPMA. For one, TWY Y is even in the real world published as a secondary contingency / emergency RWY. This does not mean that it will regularly be used by 176th ATCOs or even by uncontrolled traffic for this purpose, but the need might arise occasionally as an additional capacity consideration for special situations like an emergency during high traffic. Next, no one is eager to be No. 5, 6, 7 or 8 in line with his flight waiting in sequence on TWY Y for departure from the RWY. This prospect will be especially unattractive for RWs, who will soon want to use their special capabilities for a vertical or short rolling T/O instead of waiting an additional 10+ minutes in line on TWY Y to use the RWY.

ENBO's RWY and TWY capacities are a little low for the traffic numbers and the mix we intend to operate from there.
We should make best use of them right from the start, in order not to start with unnecessary delays and bottle-necks. right from the very first TRMA training event.
I'm not saying that RWs will by default have to use Helipad, FATO and TLOF Areas or TWY W for take-offs and landings.
Of course they will get to depart from and arrive on the main RWY as long as it's capacity is not maxed out.
But i'm saying that the contingency to efficiently use alternative areas for RW departures and arrivals should be built in right from the start, in the best interest of the RWs and the whole Wing alike. Same goes for a more even distribution of taxiing traffic between the two parallel TWYs north and south of the RWY.

I get the RWs sentiments of not wanting to be separated from the rest of the Wing or regarding realism in the visuals by operating from parts of the aerodrome that were designed for civilian use. But just Iike Neck, I don't see it this way.
When taxiing on TWY W, you RWs and future large FWs will be just as close to departing and arriving Wing mates as if you were when taxiing on TWY Y. All of ENBO is ours completely to make best use of - so from this perspective, if I was you, I'd be jumping at the occasion to occupy those huge paved and ideal for any RW-ops areas and facilities in the former civilian North of the airbase.

Sidenote:
I'm opposed to Neck's vision to scatter HPMA spawnpoint for all platforms and squadrons in a wild mix all over all shelter loops.
It is way more efficient (and realistic ;-) to have squadron's shelters grouped together and flights' ships only to be scattered across those squadrons' shelter areas - instead of forcing every flight to find each other and rejoin on C-5 or the Last Chances from all across the airbase. The ground situation would be insane in the latter case, with lots of opposite blocking situations in the shelter loops and on the parallel TWYs by single ships going in all directions to rejoin somewhere with their flight members.

The whole current ENBO Spawnpoint Discussion can be boilt down to a very basic decision between two different philosophies:

1. Do we start out as realistically as possible by cramping as much of the whole Wing into the real world southern military area of the aerodrome as long as practicable? This option maybe has a nicer feel and visuals, but will require more compromises and bring way more capacity issues right from the start, like e.g. traffic volume on TWY Y, C-5 Ramp not usable for all Wing traffic and RWs having to spawn on the grass. This design philosophy has lots of potential for future conflict and discussion because every future change like e.g. the addition of a new squadron will make it necessary to shuffle spawnpoints for existing squadrons, to re-asses, discuss, decide and re-distribute facilities and areas. 

or

2. Do we all regard the whole aerodrome as our exclusive property and home, and start out right now from the beginning with a mostly ideal distribution of assets and facilities, but with a slightly less realistic feel. This option would plant every category of airframe and its operation into a certain core area of the base, with potential for growth left and right and around the existing usage areas. HPMAs in the shelter loops, aggressors in the WHISKEY area, future FW transports on the main Apron near the Terminal, RWs around the Helipad and on the GA area. All categories would have the potential for growth without initially infringing with another category. It would not be about separation from each other but about capacities, for movement as well as for growth. And about peace as well, where everyone gets to keep his cozy home and bastion for a long time, whithout having to argue and fight against moving upon establishment of each new squadron...

**Comment by 132nd-Erro** [comment]
>  The argument that TWY W is not wide enough for rolling take-offs & landings is operational nonsense regarding a TWY width of 23m (31m incl. shoulders) versus the wheel widths and rotor diameters (H64 14,6m; H47 18m) of present and future RWs.

The nonsense here is that it's about the rotor diameter or width of the wheels. 

A sidetrack to the issue at hand, but just to offer the perspective of why:
it is not uncomming to drift laterally during a rolling take-off. The extra width of a runway for rolling take-offs has to do with extra space and margins for safety. The shoulder of the taxiway should not be used as the safety margin as there are lights sticking out. On the runway the lights are in the ground such that aircraft can roll over them. 

The tail-wheel is locked during rolling take-off, such that the helicopter will travel the direction it is facing. Minimal deviations from alignment with the runway heading can cause the helicopter to drift towards the sides of the runway during take-off. This is possible to compensate for with pedal input, even if the tail-wheel is locked, but this compensation is not instantaneous. 

![image](https://github.com/132nd-vWing/TRMA/assets/101829260/3bdc267a-59c2-41f4-843f-8a6bc779f6d1)

![image](https://github.com/132nd-vWing/TRMA/assets/101829260/cfc6bb69-b245-4460-bd1b-9e7767cbefd2)

**Comment by 132ndNeck** [comment]
> The ground situation would be insane in the latter case, with lots of opposite blocking situations in the shelter loops and on the parallel TWYs by single ships going in all directions to rejoin somewhere with their flight members

Flights will be grouped together. But not all flights of the squadron (so 4x 4ship F-16 flights will not be grouped together in one area for the 388th for example).

**Comment by Shadoga** [comment]
Roger, however nothing would speak against it, imho.
Having only one squadron in all of LIMA and another one in GOLF would do no harm and be like they do it in reality.
For RWY07, the LIMAs have the shorter taxi distance, for RWY25 the GOLFs - it's leveled out over the trainings with changing wind directions, no need to regard one area more advantageous than the other.
Of course, GOLF could be shared if two squadron's don't require more than 16 spawnpoints combined.
