### ISSUE TITLE
495th Requirements

### ISSUE THREAD

**Issue by Heidana** [132nd-vWing/TRMA#9]
I will ask the team to put down their thoughts. 
One requirement I really would like to see is an area that is suitable for a deep strike mission with an area for a TFR ingress /egress.

**Comment by 132nd-FurFace** [comment]
1.  Strongly second a range which would enable deep strike training using the TFR.
2. A basic range that is big enough to handle fast jets, set up like Range 4, but much bigger so that fast jets are not compromised by its small size - i.e. not exceeding the range limits due to speed.  Include basic bombing circles, strafe pit and a selection of IFV/MBT/BTR etc dispersed throughout the range. 
3. An air to air range, where there is a difficulty is easy/medium/hard selection- reflected in the red aircraft’s skill.  Random spawning within the MOA and a selectable number of opponents.

**Comment by hbjonsson** [comment]
to add:
1. A range suitable for pop-patterns. 
2. An electronic combat (capable) range (ECR) range ( should be useful for other pointy noses to). Useful for SEAD/DEAD or contested attacks. There need to be several ways to approach the target so that there isn´t only one avenue of approach for planning.
3. Identifiable features in A-G radar ( MAP etc) , a dummy airfield?
